# Function to load and parse a .env file
function(load_env_file env_file)
    if (EXISTS "${env_file}")
        file(READ "${env_file}" ENV_CONTENT)
        string(REGEX REPLACE "\n" ";" ENV_LINES "${ENV_CONTENT}")
        foreach (line ${ENV_LINES})
            string(STRIP "${line}" line)
            string(REGEX MATCH "^[A-Za-z_][A-Za-z0-9_]*=.*" is_valid "${line}")
            if (is_valid)
                string(REPLACE "=" ";" kv_pair "${line}")
                list(GET kv_pair 0 key)
                list(GET kv_pair 1 value)
                string(STRIP "${key}" key)
                string(STRIP "${value}" value)
                set("${key}" "${value}" PARENT_SCOPE)
            endif ()
        endforeach ()
    else ()
        message(FATAL_ERROR "The .env file '${env_file}' does not exist.")
    endif ()
endfunction()
