name: Build (Reusable)

on:
    workflow_call:
        inputs:
            os:
                required: true
                type: string
            build_type:
                required: true
                type: string
            upload_artifacts:
                description: Upload binaries
                required: false
                type: boolean
                default: false

jobs:
    CMake:
        name: ${{ inputs.os }} ${{ inputs.build_type }} Build
        if: ${{ always() }}
        runs-on: ${{ inputs.os }}
        env:
            BUILD_TYPE: ${{ inputs.build_type }}
        steps:
            -   name: Checkout Repo
                uses: actions/checkout@v4

            -   name: Clone JUCE
                uses: actions/checkout@v4
                with:
                    repository: juce-framework/JUCE
                    ref: 2f980209cc4091a4490bb1bafc5d530f16834e58
                    path: ${{ runner.workspace }}/rotor/JUCE

            -   name: Configure JUCE
                working-directory: ${{ runner.workspace }}/rotor/JUCE
                run: cmake -B bin . -DCMAKE_BUILD_TYPE=${{ inputs.build_type }}

            -   name: Build JUCE
                working-directory: ${{ runner.workspace }}/rotor/JUCE
                run: cmake --build bin --parallel 8

            -   name: Precompile Rotor
                working-directory: ${{ runner.workspace }}/rotor
                run: chmod +x ./scripts/precompile.sh && ./scripts/precompile.sh

            -   name: Configure Rotor
                working-directory: ${{ runner.workspace }}/rotor
                run: cmake -B bin . -DCMAKE_BUILD_TYPE=${{ inputs.build_type }}

            -   name: Build Rotor
                working-directory: ${{ runner.workspace }}/rotor
                run: cmake --build bin --config ${{ inputs.build_type }} --target Rotor_All --parallel 8

            -   name: Upload VST3 (Windows)
                if: ${{ inputs.upload_artifacts && inputs.os == 'windows-2022' }}
                uses: actions/upload-artifact@v4
                with:
                    name: Rotor-Windows
                    path: bin/Rotor_artefacts/${{ inputs.build_type }}/VST3/Rotor.vst3/Contents/x86_64-win/Rotor.vst3

            - name: Move Binaries (MacOS)
              if: ${{ inputs.upload_artifacts && inputs.os == 'macos-13' || inputs.os == 'macos-13-xlarge' }}
              run: |
                  mkdir -p dist && \
                  mv bin/Rotor_artefacts/${{ inputs.build_type }}/VST3/Rotor.vst3 dist && \
                  mv bin/Rotor_artefacts/${{ inputs.build_type }}/AU/Rotor.component dist

            - name: Upload AU & VST3 (MacOS)
              if: ${{ inputs.upload_artifacts && inputs.os == 'macos-13' || inputs.os == 'macos-13-xlarge' }}
              uses: actions/upload-artifact@v4
              with:
                  name: Rotor-macOS
                  path: dist/*
