name: Build (CI)

on:
    pull_request:
    push:
        branches: ['main', 'develop']

jobs:
    Trigger:
        name: Trigger ${{ inputs.os }} ${{ inputs.build_type }} Builds
        uses: ./.github/workflows/build.reusable.yml
        if: ${{ always() }}
        strategy:
            fail-fast: true
            matrix:
                os: ['macos-13', 'macos-13-xlarge', 'windows-2022']
        with:
            os: ${{ matrix.os }}
            build_type: Release
