name: Build

on:
    workflow_dispatch:
        inputs:
            build_type:
                description: Target build environment, e.g. Release, Debug
                required: true
                type: string

jobs:
    Trigger:
        name: Trigger ${{ inputs.os }} ${{ inputs.build_type }} Builds
        uses: ./.github/workflows/build.reusable.yml
        if: ${{ always() }}
        strategy:
            fail-fast: false
            matrix:
                os: ['macos-13', 'macos-13-xlarge', 'windows-2022']
        with:
            os: ${{ matrix.os }}
            build_type: ${{ inputs.build_type }}
            upload_artifacts: ${{ true }}
