name: Build

on:
    workflow_dispatch:
        inputs:
            build_type:
                description: Target plugin build environment
                required: true
                type: choice
                default: Release
                options:
                    - Release
                    - Debug
            upload_artifacts:
                description: Upload plugin binaries
                required: false
                type: boolean
                default: true

jobs:
    Trigger:
        name: Trigger ${{ inputs.os }} ${{ inputs.build_type }} Builds
        uses: ./.github/workflows/build.reusable.yml
        if: ${{ always() }}
        strategy:
            fail-fast: true
            matrix:
                os: ['macos-13', 'windows-2022']
        with:
            os: ${{ matrix.os }}
            build_type: ${{ inputs.build_type }}
            upload_artifacts: ${{ inputs.upload_artifacts }}
