name: Build (Test)

on:
    workflow_dispatch:
        inputs:
            build_type:
                description: Target build environment, e.g. Release, Debug
                required: true
                type: string

jobs:
    Trigger:
        name: Trigger ${{ inputs.os }} ${{ inputs.build_type }} Build
        uses: ./.github/workflows/build.reusable.yml
        if: ${{ always() }}
        strategy:
            fail-fast: false
            matrix:
                os: ['MacOS', 'Windows']
        with:
            os: ${{ matrix.os }}
            build_type: ${{ inputs.build_type }}
            upload_artifacts: true
