name: Build (CI)

on:
  pull_request:
  push:
    branches: [ 'main', 'develop' ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  Build:
    name: Build ${{ inputs.build_type }} (${{ inputs.os }})
    uses: ./.github/workflows/reusable.build.yml
    strategy:
      fail-fast: true
      matrix:
        os: [ 'macos-14', 'windows-2022' ]
    with:
      os: ${{ matrix.os }}
      build_type: Release
