name: rotor

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    env:
      BUILD_TYPE: Release

    steps:
    - name: "Preparation"
      uses: actions/checkout@v2

    - name: "1/7: Clone (JUCE)"
      uses: actions/checkout@v2
      with:
        repository: juce-framework/JUCE
        ref: 2f980209cc4091a4490bb1bafc5d530f16834e58
        path: ${{runner.workspace}}/rotor/JUCE
  
    # JUCE
    - name: "2/7: Preprocessor Definitions"
      working-directory: ${{runner.workspace}}/rotor/JUCE
      run: perl -i -pe "s/#define JUCE_MODAL_LOOPS_PERMITTED.*/#define JUCE_MODAL_LOOPS_PERMITTED 1/" modules/juce_core/system/juce_PlatformDefs.h

    - name: "3/7: Configuration (JUCE)"
      working-directory: ${{runner.workspace}}/rotor/JUCE
      run: cmake -B bin .

    - name: "4/7: Build (JUCE)"
      working-directory: ${{runner.workspace}}/rotor/JUCE
      run: cmake --build bin

    # Rotor
    - name: "5/7: Precompilation (Rotor)"
      working-directory: ${{runner.workspace}}/rotor
      run: chmod +x ./scripts/precompile.sh && ./scripts/precompile.sh

    - name: "6/7: Configuration (Rotor)"
      working-directory: ${{runner.workspace}}/rotor
      run: cmake -B bin .

    - name: "7/7: Build (Rotor)"
      working-directory: ${{runner.workspace}}/rotor
      run: cmake --build bin --config ${{ env.BUILD_TYPE }} --target Rotor_All
