name: Package (Test)

on: workflow_dispatch

jobs:
  Build:
    name: Build Release (${{ matrix.os }})
    uses: ./.github/workflows/build.reusable.yml
    strategy:
      fail-fast: false
      matrix:
        os: [ 'macos-13' , 'windows-2022' ]
    with:
      os: ${{ matrix.os }}
      build_type: Release
      upload_artifacts: ${{ true }}

  Package:
    name: Package ${{ matrix.os }}
    uses: ./.github/workflows/package.reusable.yml
    needs: [ Build ]
    strategy:
      fail-fast: false
      matrix:
        os: [ 'macos-13' , 'windows-2022' ]
    with:
      os: ${{ matrix.os }}
      plugin_name: Rotor
      plugin_version: 1.0.0
