name: Package (Reusable)

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

defaults:
  run:
    shell: bash

jobs:
  Package:
    name: Package (${{ inputs.os }})
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Import Environment Variables
        run: |
          source plugin.env
          echo "COMPANY_NAME=$COMPANY_NAME" >> $GITHUB_ENV
          echo "COMPANY_WEBSITE=$COMPANY_WEBSITE" >> $GITHUB_ENV
          echo "PLUGIN_NAME=$PLUGIN_NAME" >> $GITHUB_ENV
          echo "PLUGIN_CODE=$PLUGIN_CODE" >> $GITHUB_ENV
          echo "PLUGIN_VERSION=$PLUGIN_VERSION" >> $GITHUB_ENV
          echo "PLUGIN_BUNDLE_ID=$PLUGIN_BUNDLE_ID" >> $GITHUB_ENV

      - name: Set Environment Variables
        run: |
          echo "VST3_PATH=${{ env.PLUGIN_NAME }}.vst3" >> $GITHUB_ENV
          echo "AU_PATH=${{ env.PLUGIN_NAME }}.component" >> $GITHUB_ENV
          echo "INSTALLER_NAME=${{ env.PLUGIN_NAME }}-${{ env.PLUGIN_VERSION }}" >> $GITHUB_ENV
          echo "ARTIFACT_NAME=${{ env.PLUGIN_NAME }}-${{ env.PLUGIN_VERSION }}-${{ runner.os }}" >> $GITHUB_ENV

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.PLUGIN_NAME }}-${{ runner.os }}

      - name: Delete Artifacts
        uses: geekyeggo/delete-artifact@v5
        with:
          name: ${{ env.PLUGIN_NAME }}-${{ runner.os }}

      - name: Import Certificates (MacOS)
        uses: apple-actions/import-codesign-certs@v3
        if: ${{ runner.os == 'macOS' }}
        with:
          p12-file-base64: ${{ secrets.DEVELOPER_ID_CERTIFICATIONS }}
          p12-password: ${{ secrets.DEVELOPER_ID_CERTIFICATIONS_PASSWORD }}

      - name: Sign Binaries (MacOS)
        if: ${{ runner.os == 'macOS' }}
        run: |
          codesign --force -s "${{ secrets.DEVELOPER_ID_APP }}" -v "${{ env.VST3_PATH }}" --deep --strict --options=runtime --timestamp
          codesign --verify --deep --strict --verbose=2 "${{ env.VST3_PATH }}"
          codesign --force -s "${{ secrets.DEVELOPER_ID_APP }}" -v "${{ env.AU_PATH }}" --deep --strict --options=runtime --timestamp
          codesign --verify --deep --strict --verbose=2 "${{ env.AU_PATH }}"

      - name: Download Packages (MacOS)
        if: ${{ runner.os == 'macOS' }}
        run: wget http://s.sudre.free.fr/Software/files/Packages.dmg

      - name: Mount Packages (MacOS)
        if: ${{ runner.os == 'macOS' }}
        run: hdiutil attach Packages.dmg

      - name: Install Packages (MacOS)
        if: ${{ runner.os == 'macOS' }}
        run: sudo installer -pkg /Volumes/Packages\ 1.2.10/Install\ Packages.pkg -target /

      - name: Build Installer (MacOS)
        if: ${{ runner.os == 'macOS' }}
        run: |
          PKGPROJ_FILE="packaging/$PLUGIN_NAME.pkgproj"
          sed -i "s/{{PLUGIN_VERSION}}/$PLUGIN_VERSION/g" "$PKGPROJ_FILE"
          packagesbuild "$PKGPROJ_FILE"

      - name: Sign Installer (MacOS)
        if: ${{ runner.os == 'macOS' }}
        run: |
          mkdir -p packaging/build/signed
          productsign -s "${{ secrets.DEVELOPER_ID_INSTALLER }}" "packaging/build/${{ env.PLUGIN_NAME }}.pkg" "packaging/build/signed/${{ env.PLUGIN_NAME }}.pkg"
          pkgutil --check-signature "packaging/build/signed/${{ env.PLUGIN_NAME }}.pkg"

      - name: Package Installer (MacOS)
        if: ${{ runner.os == 'macOS' }}
        run: |
          # Setup tools and directories
          python3 -m pip install setuptools --break-system-packages
          npm install -g appdmg
          mkdir -p packaging/dmg
          mv packaging/README.pdf packaging/dmg
          mv packaging/build/signed/${{ env.PLUGIN_NAME }}.pkg packaging/dmg
          
          # Create the .dmg
          cd packaging && appdmg dmg.json "${{ env.INSTALLER_NAME }}.dmg"
          codesign -s "${{ secrets.DEVELOPER_ID_APP }}" --timestamp -i ${{ env.PLUGIN_BUNDLE_ID }} --force "${{ env.INSTALLER_NAME }}.dmg"
          xcrun notarytool submit "${{ env.INSTALLER_NAME }}.dmg" --apple-id ${{ secrets.APPLE_NOTARIZATION_USERNAME }} --password ${{ secrets.APPLE_NOTARIZATION_PASSWORD }} --team-id ${{ secrets.DEVELOPER_TEAM_ID }} --wait
          xcrun stapler staple "${{ env.INSTALLER_NAME }}.dmg"

      - name: Upload Installer (MacOS)
        if: ${{ runner.os == 'macOS' }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: packaging/${{ env.INSTALLER_NAME }}.dmg

      - name: Cache IPP (Windows)
        if: ${{ runner.os == 'Windows' }}
        id: cache-ipp
        uses: actions/cache@v4
        with:
          key: ipp-v5
          path: C:\Program Files (x86)\Intel

      - name: Install IPP (Windows)
        if: ${{ runner.os == 'Windows' && steps.cache-ipp.outputs.cache-hit != 'true' }}
        run: |
          curl --output oneapi.exe https://registrationcenter-download.intel.com/akdlm/IRC_NAS/b4adec02-353b-4144-aa21-f2087040f316/w_ipp_oneapi_p_2021.11.0.533_offline.exe
          ./oneapi.exe -s -x -f oneapi
          ./oneapi/bootstrapper.exe -s -c --action install --components=intel.oneapi.win.ipp.devel --eula=accept -p=NEED_VS2022_INTEGRATION=1 --log-dir=.  

      - name: Save IPP Cache (Windows)
        if: ${{ runner.os == 'Windows' && steps.cache-ipp.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@v4
        with:
          key: ipp-v5
          path: C:\Program Files (x86)\Intel

      - name: Build Installer (Windows)
        if: ${{ runner.os == 'Windows' }}
        run: |
          ISS_FILE="packaging/$PLUGIN_NAME.iss"
          sed -i "s/{{PLUGIN_NAME}}/$PLUGIN_NAME/g" "$ISS_FILE"
          sed -i "s/{{PLUGIN_VERSION}}/$PLUGIN_VERSION/g" "$ISS_FILE"
          sed -i "s/{{COMPANY_NAME}}/$COMPANY_NAME/g" "$ISS_FILE"
          
          iscc "packaging\${{ env.PLUGIN_NAME }}.iss"
          mv "packaging\Output\${{ env.INSTALLER_NAME }}.exe" .

      - name: Upload Installer (Windows)
        if: ${{ runner.os == 'Windows' }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.INSTALLER_NAME }}.exe
